language: python
python: 3.6

branches:
  only:
  - master

install:
  - export HUGO_PACKAGE=`curl -s https://api.github.com/repos/gohugoio/hugo/releases/latest | grep browser_download_url | cut -d '"' -f 4 | grep Linux-64bit.tar.gz`
  - wget $HUGO_PACKAGE
  - tar -xvf $HUGO_PACKAGE hugo
  - pip install css-html-js-minify

script:
  - ./hugo
  #- ./scripts/css-html-js-minify.py public --overwrite

deploy:
  provider: pages
  skip_cleanup: true
  github_token: ${GH_TOKEN}
  local_dir: public
